name: Build and Push Docker Image to GHCR with Incremental Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのチェックアウト
      - name: Check out the repository
        uses: actions/checkout@v3

      # 最新のタグを取得
      - name: Get latest tag
        id: get_tag
        run: |
          # 最新のタグを取得
          TAG=$(git describe --tags --abbrev=0)
          # タグが存在しない場合は v0.0.0 にする
          if [ -z "$TAG" ]; then
            echo "v0.0.0" > latest_tag
          else
            echo $TAG > latest_tag
          fi

      # タグをインクリメント
      - name: Increment tag version
        id: increment_tag
        run: |
          # 最新タグを読み込み
          TAG=$(cat latest_tag)
          # バージョン番号の最後の部分をインクリメント (例: v1.0.0 -> v1.0.1)
          IFS='.' read -r -a TAG_PARTS <<< "${TAG//v/}"
          NEW_TAG="v${TAG_PARTS[0]}.${TAG_PARTS[1]}.$((TAG_PARTS[2]+1))"
          echo "New tag: $NEW_TAG"
          echo $NEW_TAG > new_tag

      # Docker Buildxのセットアップ
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # GitHub Container Registryへのログイン
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Dockerイメージのビルドとプッシュ
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/arm64  # ARM64アーキテクチャを指定
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.increment_tag.outputs.new_tag }}

      # 新しいタグを作成してプッシュ
      - name: Create new tag
        run: |
          git tag ${{ steps.increment_tag.outputs.new_tag }}
          git push origin ${{ steps.increment_tag.outputs.new_tag }}